name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/norbert-gemes/darts-players:$IMAGE_TAG --tag ghcr.io/norbert-gemes/darts-players:latest
          docker login ghcr.io -u norbert-gemes -p ${{secrets.GHCL_TOKEN}}
          docker push ghcr.io/norbert-gemes/darts-players:$IMAGE_TAG
          docker push ghcr.io/norbert-gemes/darts-players:latest
